version: "3.1"
services:
  postgres:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_USER: phoenix
      POSTGRES_DB: nano_planner_dev
      POSTGRES_PASSWORD: phoenix
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: phoenix
      MYSQL_PASSWORD: phoenix
      MYSQL_DATABASE: nano_planner_dev
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: bash
    environment:
      MIX_ENV: "dev"
      PORT: "4000"
    volumes:
      - ./apps:/apps
    working_dir: /apps
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - mysql
    tty: true

volumes:
  postgres_data:
  mysql_data:
